config/routes.rb
Rails.application.routes.draw do


  # get 'work/choose_image'
  #
  # get 'work/choose_theme'
  #
  # get 'work/display_theme'

  resources :values
  resources :users
  resources :themes
  resources :images

  root 'work#index'

  # root 'main#task'

  # main
  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'
  match 'task',     to: 'main#task',            via: 'get'


  match 'work',             to: 'work#index',                  via: 'get'
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',      via: :post





  # main#tasks #
  match 'task',               to: 'main#task',              via: 'get'

  # task 1 #
  match 'task_one',           to: 'main#task_one',          via: 'get'
  match 'display_wheather',   to: 'main#display_wheather',  via: 'get'

  # task 2 #
  match 'search_form_jand',                   to: 'main#search_form_jand',                  via: 'get'
  # match 'task_two/search_form_jand',                 to: 'main#search_form_jand',                via: 'get'
  # match 'task_two/display_search_results',   to: 'main#display_search_results',  via: 'get'
  match 'store_search_query',   to: 'main#store_search_query',  via: 'get'





  # get 'main/index'
  #
  # get 'main/help'
  #
  # get 'main/contacts'
  #
  # get 'main/about'
  #
  # get 'main/task'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  # skip_before_filter  :authenticate
  require 'json'

  include WeatherDataProcessing     # task 1
  include SearchResultsProcessing   # task 2

  def index


  end

  def help
  end

  def contacts
  end

  def about
  end

  def task
  end

  def task_one
    logger.info "In task_one"
  end

  def display_wheather
    logger.info "In display_wheather"

    @cond_wheather = []
    @title = ""
    unless params[:cond_wheather].blank?
      @cond_wheather, @title = make_weather_data(params[:cond_wheather])
    end
  end

  def search_form_jand
    logger.info "In search_form_jand"

    value = params[:value]
    logger.info "In search_form_jand: value = #{value} "

    content = params[:content]
    logger.info "In search_form_jand: content = #{content} "

  end

  def store_search_query
    query = params[:query]
    logger.info "In store_search_query: query = #{query} "
    query_text = "Search query = #{query}"
    logger.info "In store_search_query: query_text = #{query_text} "
    respond_to do |format|
      if query.blank?
        format.html {  render nothing: true, status: :unprocessable_entity }
        format.json {}
      else
        format.json { render json:  { query_text: query_text,
                                      notice: 'Successfully listed to next'} }
      end
    end
  end


  def display_search_results
    # @cond_wheather = []
    # @title = ""
    # unless params[:cond_wheather].blank?
    #   @cond_wheather, @title = make_weather_data(params[:cond_wheather])
    # end
  end



end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/about.html.haml
%h1 Main#about
%p Find me in app/views/main/about.html.haml

app/views/main/contacts.html.haml
%h1 Main#contacts
%p Find me in app/views/main/contacts.html.haml

app/views/main/display_search_results.html.haml
-#/**
-# * Created by aleks_i on 25.03.16.
-# */

- provide(:title, "Display")
%h3.test_weather
  Результаты поиска для поискового запроса: #{@search_query.inspect}
  %br
  (https://developer.yahoo.com)
  %br
  %hr

- if @cond_wheather.blank?
  %table{ :style => "table-layout: auto; title: 'No Values results...';" }
    .results
      %h2=  "no values"
      %h2=  "no weather prognose"
  %br
  %hr
- else
  %table{ :style => "table-layout: auto; title: 'All images expert values';" }
    .results
    %tr{ :style => "font-family: $helvetica; font-size: 1.3em; " }
      %th date
      %th day
      %th T, high
      %th T, low
      %th wheather
      %th image

    - @cond_wheather.take(7).each do |one_day_weather|
      %tr.weather_one_row
        %td{ :style => "text-align: left; width: 7em" }= one_day_weather['date']
        %td{ :style => "color: rgba(122, 13, 75, 1);" }= one_day_weather['day']

        %td= one_day_weather['high']
        %td= one_day_weather['low']
        %td= one_day_weather['text']
        %td= image_tag('/assets/weather/' + one_day_weather['image'], {:width => "53", :height =>"47", title: "Weather image"} )

    -#= paginate @cond_wheather_paged
= link_to "Return to Task List", task_path,  class: "btn btn-lg btn-primary", title: "Go to main page"
%br
%br

app/views/main/display_wheather.html.haml
-#/**
-# * Created by aleks_i on 25.03.16.
-# */

- provide(:title, "Display")
%h3.test_weather
  Прогноз погоды для:  #{@title.inspect}
  %br
  (https://developer.yahoo.com)
  %br
  %hr

- if @cond_wheather.blank?
  %table{ :style => "table-layout: auto; title: 'No Values results...';" }
    .results
      %h2=  "no values"
      %h2=  "no weather prognose"
  %br
  %hr
- else
  %table{ :style => "table-layout: auto; title: 'All images expert values';" }
    .results
    %tr{ :style => "font-family: $helvetica; font-size: 1.3em; " }
      %th date
      %th day
      %th T, high
      %th T, low
      %th wheather
      %th image

    - @cond_wheather.take(7).each do |one_day_weather|
      %tr.weather_one_row
        %td{ :style => "text-align: left; width: 7em" }= one_day_weather['date']
        %td{ :style => "color: rgba(122, 13, 75, 1);" }= one_day_weather['day']

        %td= one_day_weather['high']
        %td= one_day_weather['low']
        %td= one_day_weather['text']
        %td= image_tag('/assets/weather/' + one_day_weather['image'], {:width => "53", :height =>"47", title: "Weather image"} )

    -#= paginate @cond_wheather_paged
= link_to "Return to Task List", task_path,  class: "btn btn-lg btn-primary", title: "Go to main page"
%br
%br

app/views/main/help.html.haml
%h1 Main#help
%p Find me in app/views/main/help.html.haml

app/views/main/index.html.haml
%h1 Main#index
%p Find me in app/views/main/index.html.haml

app/views/main/task.html.haml
- provide(:title, "Test")

-#%h1= t('.contacts_title')
%h1= 'Select Task'

.about-copy

  .select_theme
    -#= render 'main/button_test_select'
    -#, locale: @current_locale

  %h3.list
    Task 1:
    = link_to ' Базовые умения верстки и обмена данными.', task_one_path,  remote: true
    -#,  :format => "js"
    %br
    .test_task
      Eсть прогноз погоды по ссылке в формате JSON: https://developer.yahoo.com/weather/
      %br
      1) Отрисовать столбиковую диаграмму на неделю;
      %br
      2) К каждому столбику добавить изображение состояния погоды - облачность, дождь и т.д.
    %br

    .test_start_btn
    -#  = render 'main/test_start_btn'
      -#, locale: @current_locale


    -#.select_theme
    -#= render 'work/button_theme_select', locale: @current_locale

    %br

    Task 2:
    = link_to ' Динамическое сохранение поискового запроса', search_form_jand_path
    %br
    .test_task
      1) Прогрузить страницу яндекса и изменить все текстовое содержание ниже поисковой строки
      %br
      (перевести на английский (верхняя часть на русском, нижняя на английском);
      %br
      (Страница не должна быть идентична - только визуально похожа)
      %br
      2) Сохранить запрос при вводе в форму поиска с копии сайта.
    %br
    %br

    Task 2a:
    = link_to ' Динамическое отображение результатов поиска', search_form_jand_path
    %br
    .test_task
      1) Прогрузить измененную страницу яндекса
      %br
      2) После ввода запроса поиска перехватить результаты и отобразить в рандомном порядке результат поиска
    %br
    %br

  -#Task 3:
    -#= link_to ' Динамическая замена страницы', about_path
    -#%br
    .test_task
    -#Сделайте полную визуальную копию главной страницы сайта http://www.bankofamerica.com без никакого обращения на сайт банка - даже за js либами
    %br
    -#1) Поменять местами следующие данные: "Access your accounts","Pay bills","Set up alerts", Maketransfers" в случайном порядке вместе с картинками;
    %br
    -#2) Сохранить учетные данные при вводе в форму авторизации с копии сайта.
    -#%br
    -#%br


  %i.fa.fa-flag.iconsMain{ style: "color: #C44BB4; font-size: 4em; position: relative; left: 50%;" }

app/views/main/task_one.js.erb
//var jsonDataLink = '<%= raw @json_data_link %>';
//console.log("IN task_one.js: jsonDataLink = " + jsonDataLink);


////var taskData = '<%= raw @composite_results %>';
//var compositeResults = '<%= @composite_results %>';
//console.log("IN task_one.js: compositeResults = " + compositeResults);

var askSiteForJson = function(url) {
//  stopImmediatePropagation(); // when ajax deal with events:
// would stop the event from bubbling to parent elements,

  $.ajax({
    type: "get",
    url: url,
    dataType: 'json'
  }).done(function(data_return) {
    console.log(data_return);
    var hashJson = JSON.stringify(data_return);
//    console.log("success ajax:  " + hashJson);
//    var obj = JSON.parse(hashJson);
//    console.log(obj);
//    var condWeather = obj.query.results.channel.item.forecast;
//    console.log(condWeather);

// to pass params to controller and render action#view

// alternative # 1: with use of extra action#view

//    $.ajax({
//      type: "post",
//      url: "/task_one_view?cond_wheather=" + condWeather,
//      data: { cond_wheather: condWeather}
//    }).done(function(data_return) {
//      console.log("success in sendJsontoView ");
//      console.log("In sendJsontoView: data_return  = " + data_return);
//    })
//    .fail(function (data_return) {
//      console.log("error In sendJsontoView: data_return = " + data_return);
//    });


// alternative # 2:
//    window.location.href = "display_wheather?cond_wheather=" + condWeather ;
    window.location.href = "display_wheather?cond_wheather=" + JSON.stringify(data_return) ;

  })
  .fail(function (data_return) {
    console.log("Error in askSiteForJson(): data_return = " + data_return);
  });
};

var yahooURL = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nome%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
//    "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nome%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
askSiteForJson(yahooURL);

app/views/main/task_two0.js.erb
console.log("In Task_Two");
alert("Two");


//var jsonDataLink = '<%= raw @json_data_link %>';
//console.log("IN task_one.js: jsonDataLink = " + jsonDataLink);


//var taskData = '<%= raw @composite_results %>';
//var compositeResults = '<%= @composite_results %>';
//console.log("IN task_one.js: compositeResults = " + compositeResults);

var askSiteForJson = function(url) {
//  stopImmediatePropagation(); // when ajax deal with events:
// would stop the event from bubbling to parent elements,

  $.ajax({
    type: "get",
    url: url,
    dataType: 'json'
  }).done(function(data_return) {
//    console.log(data_return);
//    var hashJson = JSON.stringify(data_return);
//    console.log("success ajax:  " + hashJson);
//    var obj = JSON.parse(hashJson);
//    console.log(obj);
//    var condWeather = obj.query.results.channel.item.forecast;
//    console.log(condWeather);

// to pass params to controller and render action#view

// alternative # 1: with use of extra action#view

//    $.ajax({
//      type: "post",
//      url: "/task_one_view?cond_wheather=" + condWeather,
//      data: { cond_wheather: condWeather}
//    }).done(function(data_return) {
//      console.log("success in sendJsontoView ");
//      console.log("In sendJsontoView: data_return  = " + data_return);
//    })
//    .fail(function (data_return) {
//      console.log("error In sendJsontoView: data_return = " + data_return);
//    });


// alternative # 2:
//    window.location.href = "display_wheather?cond_wheather=" + condWeather ;
    window.location.href = "display_wheather?cond_wheather=" + JSON.stringify(data_return) ;

  })
      .fail(function (data_return) {
        console.log("Error in askSiteForJson(): data_return = " + data_return);
      });
};

var yahooURL = "https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22nome%2C%20ak%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys";
askSiteForJson(yahooURL);