config/routes.rb
Rails.application.routes.draw do


  # get 'work/choose_image'
  #
  # get 'work/choose_theme'
  #
  # get 'work/display_theme'

  resources :values
  resources :users
  resources :themes
  resources :images

  root 'work#index'

  # root 'main#task'

  # main
  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'
  match 'task',     to: 'main#task',            via: 'get'


  match 'work',             to: 'work#index',                  via: 'get'
  match 'choose_theme',     to: 'work#choose_theme',      via: :get
  match 'display_theme',    to: 'work#display_theme',      via: :post





  # main#tasks #
  match 'task',               to: 'main#task',              via: 'get'

  # task 1 #
  match 'task_one',           to: 'main#task_one',          via: 'get'
  match 'display_wheather',   to: 'main#display_wheather',  via: 'get'

  # task 2 #
  match 'search_form_jand',                   to: 'main#search_form_jand',                  via: 'get'
  # match 'task_two/search_form_jand',                 to: 'main#search_form_jand',                via: 'get'
  # match 'task_two/display_search_results',   to: 'main#display_search_results',  via: 'get'
  match 'store_search_query',   to: 'main#store_search_query',  via: 'get'





  # get 'main/index'
  #
  # get 'main/help'
  #
  # get 'main/contacts'
  #
  # get 'main/about'
  #
  # get 'main/task'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flash.html.haml
-#- flash.each do |type, message|
-#  .flash{class: type}
-#    = message

- flash.each do |type, message|
  - if type == 'link'
    .flash{class: message[:type]}
      .container
        = link_to message[:message], message[:link]
        %a.close{href:'#', onclick: "$('.flash').slideUp();"}= fa_icon "close"
  - else
    :javascript
      Notification.#{type}("#{message}")

    .flash{class: type}
      .container
        = message
        %a.close{href:'#', onclick: "$('.flash').slideUp();"}= fa_icon "close"

app/views/shared/_footer.html.haml
%footer.footer
  -#%p Experteese
    -#{style: " display:inline-block; font-size: 1em"}

    -#2016
  -#%small
  -#  The
  -#  %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
  -#  by
  -#  %a{:href => "http://www.michaelhartl.com/"} Michael Hartl

  %h3{style: "color: #c4f7ff; font-size: 1.5em; position: relative; left: 20%; margin-top: .55em;"}
    Stones
    %i.fa.fa-copyright.iconsMain{ style: " font-size: 1.3em; " }
    2016

    %p.app_notice_dev{style: " font-size: 1em; position: relative; left: 60%;"}
      %span{ style: "color: #730E15; font-size: 1.3em; position: relative; left: 11%; top: .5em;" }
        %i.fa.fa-flag.iconsMain{ style: "color: #730E15; font-size: 1em; " }
          = 'App is in Development'


  .footer_menu
    %nav
      %ul
        %li= link_to t('.about'), about_path
        %li= link_to t('.contact'), contacts_path
        -#%li
        -#  %a{:href => "http://news.railstutorial.org/"} News

app/views/shared/_header.html.haml
%header.navbar.navbar-fixed-top.navbar-inverse
  .container.header
    -#= link_to t('.logo_title'), root_path, id: "logo"
    = link_to 'Stones', root_path, id: "logo"
    .rails_logo
      = link_to image_tag("rails.png", alt: "Rails logo")

      -#%p.locale
      -#
      -#  -#.ru_link
      -#  = link_to image_tag("Russia.jpg", alt: "",  style: "width: 10%; height: 10%", title: "Русский" ), locale: :ru
      -#  -#= link_to image_tag("Russia.jpg", alt: "",  style: "width: 8%; height: 8%; " )+" РУ", locale: :ru
      -#  -#%p{style: "color: #c4f7ff"}" РУ"
      -#  -#= link_to_unless I18n.locale == :ru, "Русский", locale: :ru
      -#  -#%image_tag(style= "width: 8%; height: 8%" src= "assets/Russia.jpg")
      -#  -#|
      -#  = link_to image_tag("United_Kingdom.jpg", alt: "",  style: "width: 12%; height: 12%", title: "English"), locale: :en
      -#  -#= link_to image_tag("United_Kingdom.jpg", alt: "",  style: "width: 9%; height: 9%")+" EN", locale: :en
      -#  -#= link_to_unless I18n.locale == :en, "English", locale: :en
      -#  %b
      -#    = I18n.locale



    %nav
      %ul.nav.navbar-nav.pull-right
        %li= link_to 'Task', task_path
        %li= link_to t('.home'), root_path
        %li= link_to t('.help'), help_path
        -#- if signed_in?
        -#  -#%li= link_to "Users", '#'
        -#  %li.logged
        -#    #{current_user.email}
        -#  = gravatar_for current_user
        -#  %li#fat-menu.dropdown
        -#    %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        -#      %p
        -#        = t('.person')
        -#        %b.caret
        -#    %ul.dropdown-menu
        -#      %li= link_to t('.profile'), current_user
        -#      %li= link_to t('.settings'), '#'
        -#      %li.divider
        -#      %li
        -#        = link_to t('.sign_out'), signout_path, method: "delete"
        -#- else
        -#  %li= link_to t('.sign_in'), signin_path